/* Generated by Yosys 0.68+136 (git sha1 c30457480-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

(* top =  1  *)
(* src = "rtl/alu.v:4.1-61.10" *)
module alu(A, B, OPCODE, RESULT);
  (* src = "rtl/alu.v:5.23-5.24" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "rtl/alu.v:6.23-6.24" *)
  input [7:0] B;
  wire [7:0] B;
  (* src = "rtl/alu.v:7.23-7.29" *)
  input [2:0] OPCODE;
  wire [2:0] OPCODE;
  (* src = "rtl/alu.v:8.23-8.29" *)
  output [7:0] RESULT;
  wire [7:0] RESULT;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  (* src = "rtl/alu.v:5.23-5.24" *)
  wire _125_;
  (* src = "rtl/alu.v:5.23-5.24" *)
  wire _126_;
  (* src = "rtl/alu.v:5.23-5.24" *)
  wire _127_;
  (* src = "rtl/alu.v:5.23-5.24" *)
  wire _128_;
  (* src = "rtl/alu.v:5.23-5.24" *)
  wire _129_;
  (* src = "rtl/alu.v:5.23-5.24" *)
  wire _130_;
  (* src = "rtl/alu.v:5.23-5.24" *)
  wire _131_;
  (* src = "rtl/alu.v:5.23-5.24" *)
  wire _132_;
  (* src = "rtl/alu.v:6.23-6.24" *)
  wire _133_;
  (* src = "rtl/alu.v:6.23-6.24" *)
  wire _134_;
  (* src = "rtl/alu.v:6.23-6.24" *)
  wire _135_;
  (* src = "rtl/alu.v:6.23-6.24" *)
  wire _136_;
  (* src = "rtl/alu.v:6.23-6.24" *)
  wire _137_;
  (* src = "rtl/alu.v:6.23-6.24" *)
  wire _138_;
  (* src = "rtl/alu.v:6.23-6.24" *)
  wire _139_;
  (* src = "rtl/alu.v:6.23-6.24" *)
  wire _140_;
  (* src = "rtl/alu.v:7.23-7.29" *)
  wire _141_;
  (* src = "rtl/alu.v:7.23-7.29" *)
  wire _142_;
  (* src = "rtl/alu.v:7.23-7.29" *)
  wire _143_;
  (* src = "rtl/alu.v:8.23-8.29" *)
  wire _144_;
  (* src = "rtl/alu.v:8.23-8.29" *)
  wire _145_;
  (* src = "rtl/alu.v:8.23-8.29" *)
  wire _146_;
  (* src = "rtl/alu.v:8.23-8.29" *)
  wire _147_;
  (* src = "rtl/alu.v:8.23-8.29" *)
  wire _148_;
  (* src = "rtl/alu.v:8.23-8.29" *)
  wire _149_;
  (* src = "rtl/alu.v:8.23-8.29" *)
  wire _150_;
  (* src = "rtl/alu.v:8.23-8.29" *)
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  sky130_fd_sc_hd__nor2_1 _234_ (
    .A(_143_),
    .B(_142_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__or3b_1 _235_ (
    .A(_143_),
    .B(_142_),
    .C_N(_141_),
    .X(_168_)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(_133_),
    .B(_168_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__o21ai_0 _237_ (
    .A1(_133_),
    .A2(_134_),
    .B1(_168_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__o31ai_1 _238_ (
    .A1(_133_),
    .A2(_134_),
    .A3(_135_),
    .B1(_168_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(_136_),
    .B(_168_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nand2_1 _240_ (
    .A(_171_),
    .B(_172_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__a21oi_1 _241_ (
    .A1(_137_),
    .A2(_168_),
    .B1(_173_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nand2b_1 _242_ (
    .A_N(_138_),
    .B(_174_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__xor2_1 _243_ (
    .A(_138_),
    .B(_174_),
    .X(_176_)
  );
  sky130_fd_sc_hd__xnor2_1 _244_ (
    .A(_137_),
    .B(_173_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__xor2_1 _245_ (
    .A(_136_),
    .B(_171_),
    .X(_178_)
  );
  sky130_fd_sc_hd__xor2_1 _246_ (
    .A(_135_),
    .B(_170_),
    .X(_179_)
  );
  sky130_fd_sc_hd__xor2_1 _247_ (
    .A(_134_),
    .B(_169_),
    .X(_180_)
  );
  sky130_fd_sc_hd__nand2b_1 _248_ (
    .A_N(_125_),
    .B(_133_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__xor2_1 _249_ (
    .A(_126_),
    .B(_180_),
    .X(_182_)
  );
  sky130_fd_sc_hd__nand2_1 _250_ (
    .A(_181_),
    .B(_182_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__maj3_1 _251_ (
    .A(_126_),
    .B(_180_),
    .C(_181_),
    .X(_184_)
  );
  sky130_fd_sc_hd__xor2_1 _252_ (
    .A(_127_),
    .B(_179_),
    .X(_185_)
  );
  sky130_fd_sc_hd__nand2_1 _253_ (
    .A(_184_),
    .B(_185_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__maj3_1 _254_ (
    .A(_127_),
    .B(_179_),
    .C(_184_),
    .X(_187_)
  );
  sky130_fd_sc_hd__xor2_1 _255_ (
    .A(_128_),
    .B(_178_),
    .X(_188_)
  );
  sky130_fd_sc_hd__nand2_1 _256_ (
    .A(_187_),
    .B(_188_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__maj3_1 _257_ (
    .A(_128_),
    .B(_178_),
    .C(_187_),
    .X(_190_)
  );
  sky130_fd_sc_hd__xor2_1 _258_ (
    .A(_129_),
    .B(_177_),
    .X(_191_)
  );
  sky130_fd_sc_hd__nand2_1 _259_ (
    .A(_190_),
    .B(_191_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__maj3_1 _260_ (
    .A(_129_),
    .B(_177_),
    .C(_190_),
    .X(_193_)
  );
  sky130_fd_sc_hd__xor2_1 _261_ (
    .A(_130_),
    .B(_176_),
    .X(_194_)
  );
  sky130_fd_sc_hd__nand2_1 _262_ (
    .A(_193_),
    .B(_194_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__maj3_1 _263_ (
    .A(_130_),
    .B(_176_),
    .C(_193_),
    .X(_196_)
  );
  sky130_fd_sc_hd__nand2_1 _264_ (
    .A(_168_),
    .B(_175_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__xor2_1 _265_ (
    .A(_139_),
    .B(_197_),
    .X(_198_)
  );
  sky130_fd_sc_hd__nand2_1 _266_ (
    .A(_131_),
    .B(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__xor2_1 _267_ (
    .A(_131_),
    .B(_198_),
    .X(_200_)
  );
  sky130_fd_sc_hd__nor2_1 _268_ (
    .A(_196_),
    .B(_200_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nand2_1 _269_ (
    .A(_196_),
    .B(_200_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(_167_),
    .B(_202_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__nand2_1 _271_ (
    .A(_139_),
    .B(_131_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nand2b_1 _272_ (
    .A_N(_143_),
    .B(_142_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _273_ (
    .A(_141_),
    .SLEEP(_205_),
    .X(_206_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _274_ (
    .A(_141_),
    .SLEEP(_205_),
    .X(_207_)
  );
  sky130_fd_sc_hd__or3b_1 _275_ (
    .A(_141_),
    .B(_142_),
    .C_N(_143_),
    .X(_208_)
  );
  sky130_fd_sc_hd__a21oi_1 _276_ (
    .A1(_139_),
    .A2(_131_),
    .B1(_208_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__o22ai_1 _277_ (
    .A1(_139_),
    .A2(_131_),
    .B1(_207_),
    .B2(_209_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__o221ai_1 _278_ (
    .A1(_201_),
    .A2(_203_),
    .B1(_204_),
    .B2(_206_),
    .C1(_210_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor2_1 _279_ (
    .A(_193_),
    .B(_194_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nand2_1 _280_ (
    .A(_167_),
    .B(_195_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__nand2_1 _281_ (
    .A(_138_),
    .B(_130_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__a21oi_1 _282_ (
    .A1(_138_),
    .A2(_130_),
    .B1(_208_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__o22ai_1 _283_ (
    .A1(_138_),
    .A2(_130_),
    .B1(_207_),
    .B2(_214_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__o221ai_1 _284_ (
    .A1(_211_),
    .A2(_212_),
    .B1(_213_),
    .B2(_206_),
    .C1(_215_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nor2_1 _285_ (
    .A(_190_),
    .B(_191_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__nand2_1 _286_ (
    .A(_167_),
    .B(_192_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nand2_1 _287_ (
    .A(_137_),
    .B(_129_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__a21oi_1 _288_ (
    .A1(_137_),
    .A2(_129_),
    .B1(_208_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__o22ai_1 _289_ (
    .A1(_137_),
    .A2(_129_),
    .B1(_207_),
    .B2(_219_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__o221ai_1 _290_ (
    .A1(_216_),
    .A2(_217_),
    .B1(_218_),
    .B2(_206_),
    .C1(_220_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nor2_1 _291_ (
    .A(_187_),
    .B(_188_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nand2_1 _292_ (
    .A(_167_),
    .B(_189_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nand2_1 _293_ (
    .A(_136_),
    .B(_128_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__a21oi_1 _294_ (
    .A1(_136_),
    .A2(_128_),
    .B1(_208_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__o22ai_1 _295_ (
    .A1(_136_),
    .A2(_128_),
    .B1(_207_),
    .B2(_224_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__o221ai_1 _296_ (
    .A1(_221_),
    .A2(_222_),
    .B1(_223_),
    .B2(_206_),
    .C1(_225_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nor2_1 _297_ (
    .A(_184_),
    .B(_185_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__nand2_1 _298_ (
    .A(_167_),
    .B(_186_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__nand2_1 _299_ (
    .A(_135_),
    .B(_127_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__a21oi_1 _300_ (
    .A1(_135_),
    .A2(_127_),
    .B1(_208_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__o22ai_1 _301_ (
    .A1(_135_),
    .A2(_127_),
    .B1(_207_),
    .B2(_229_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__o221ai_1 _302_ (
    .A1(_226_),
    .A2(_227_),
    .B1(_228_),
    .B2(_206_),
    .C1(_230_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nor2_1 _303_ (
    .A(_181_),
    .B(_182_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__nand2_1 _304_ (
    .A(_167_),
    .B(_183_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__nand2_1 _305_ (
    .A(_134_),
    .B(_126_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__a21oi_1 _306_ (
    .A1(_134_),
    .A2(_126_),
    .B1(_208_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__o22ai_1 _307_ (
    .A1(_134_),
    .A2(_126_),
    .B1(_207_),
    .B2(_152_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__o221ai_1 _308_ (
    .A1(_231_),
    .A2(_232_),
    .B1(_233_),
    .B2(_206_),
    .C1(_153_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a21oi_1 _309_ (
    .A1(_133_),
    .A2(_125_),
    .B1(_141_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _310_ (
    .A(_133_),
    .B(_125_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__a21oi_1 _311_ (
    .A1(_141_),
    .A2(_143_),
    .B1(_142_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__xor2_1 _312_ (
    .A(_133_),
    .B(_125_),
    .X(_157_)
  );
  sky130_fd_sc_hd__nand2_1 _313_ (
    .A(_156_),
    .B(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__o31ai_1 _314_ (
    .A1(_205_),
    .A2(_154_),
    .A3(_155_),
    .B1(_158_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nor2_1 _315_ (
    .A(_132_),
    .B(_140_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__xnor2_1 _316_ (
    .A(_132_),
    .B(_140_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__o21ai_0 _317_ (
    .A1(_139_),
    .A2(_175_),
    .B1(_168_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__xor2_1 _318_ (
    .A(_160_),
    .B(_161_),
    .X(_162_)
  );
  sky130_fd_sc_hd__nand3_1 _319_ (
    .A(_199_),
    .B(_202_),
    .C(_162_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a21o_1 _320_ (
    .A1(_199_),
    .A2(_202_),
    .B1(_162_),
    .X(_164_)
  );
  sky130_fd_sc_hd__a21oi_1 _321_ (
    .A1(_132_),
    .A2(_140_),
    .B1(_141_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__o32ai_1 _322_ (
    .A1(_205_),
    .A2(_159_),
    .A3(_165_),
    .B1(_160_),
    .B2(_208_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a31o_1 _323_ (
    .A1(_167_),
    .A2(_163_),
    .A3(_164_),
    .B1(_166_),
    .X(_151_)
  );
  assign _141_ = OPCODE[0];
  assign _143_ = OPCODE[2];
  assign _142_ = OPCODE[1];
  assign _133_ = B[0];
  assign _134_ = B[1];
  assign _135_ = B[2];
  assign _136_ = B[3];
  assign _137_ = B[4];
  assign _138_ = B[5];
  assign _130_ = A[5];
  assign _129_ = A[4];
  assign _128_ = A[3];
  assign _127_ = A[2];
  assign _126_ = A[1];
  assign _125_ = A[0];
  assign _139_ = B[6];
  assign _131_ = A[6];
  assign RESULT[6] = _150_;
  assign RESULT[5] = _149_;
  assign RESULT[4] = _148_;
  assign RESULT[3] = _147_;
  assign RESULT[2] = _146_;
  assign RESULT[1] = _145_;
  assign RESULT[0] = _144_;
  assign _132_ = A[7];
  assign _140_ = B[7];
  assign RESULT[7] = _151_;
endmodule
