/* Generated by Yosys 0.68+136 (git sha1 c30457480-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

(* hdlname = "baud_tick_gen" *)
(* src = "rtl/baud_tick_gen.v:4.1-63.10" *)
module \$paramod$b7294f1997723f0618629b64f4b039e150234139\baud_tick_gen (clk, reset, bit_tick);
  (* src = "rtl/baud_tick_gen.v:8.17-8.20" *)
  input clk;
  wire clk;
  (* src = "rtl/baud_tick_gen.v:9.17-9.22" *)
  input reset;
  wire reset;
  (* src = "rtl/baud_tick_gen.v:11.17-11.25" *)
  output bit_tick;
  wire bit_tick;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  (* src = "rtl/baud_tick_gen.v:25.16-25.27" *)
  wire [31:0] bit_counter;
  sky130_fd_sc_hd__clkinv_1 _104_ (
    .A(bit_counter[22]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__clkinv_1 _105_ (
    .A(bit_counter[23]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__clkinv_1 _106_ (
    .A(bit_counter[24]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__and3_1 _107_ (
    .A(bit_counter[0]),
    .B(bit_counter[1]),
    .C(bit_counter[2]),
    .X(_074_)
  );
  sky130_fd_sc_hd__and4_1 _108_ (
    .A(bit_counter[0]),
    .B(bit_counter[1]),
    .C(bit_counter[2]),
    .D(bit_counter[3]),
    .X(_075_)
  );
  sky130_fd_sc_hd__and2_0 _109_ (
    .A(bit_counter[4]),
    .B(_075_),
    .X(_076_)
  );
  sky130_fd_sc_hd__and4_1 _110_ (
    .A(bit_counter[4]),
    .B(bit_counter[5]),
    .C(bit_counter[6]),
    .D(_075_),
    .X(_077_)
  );
  sky130_fd_sc_hd__and3_1 _111_ (
    .A(bit_counter[7]),
    .B(bit_counter[8]),
    .C(_077_),
    .X(_078_)
  );
  sky130_fd_sc_hd__and4_1 _112_ (
    .A(bit_counter[7]),
    .B(bit_counter[8]),
    .C(bit_counter[9]),
    .D(_077_),
    .X(_079_)
  );
  sky130_fd_sc_hd__and2_0 _113_ (
    .A(bit_counter[10]),
    .B(_079_),
    .X(_080_)
  );
  sky130_fd_sc_hd__and3_1 _114_ (
    .A(bit_counter[10]),
    .B(bit_counter[11]),
    .C(_079_),
    .X(_081_)
  );
  sky130_fd_sc_hd__and4_1 _115_ (
    .A(bit_counter[10]),
    .B(bit_counter[11]),
    .C(bit_counter[12]),
    .D(_079_),
    .X(_082_)
  );
  sky130_fd_sc_hd__and2_0 _116_ (
    .A(bit_counter[13]),
    .B(_082_),
    .X(_083_)
  );
  sky130_fd_sc_hd__and3_1 _117_ (
    .A(bit_counter[13]),
    .B(bit_counter[14]),
    .C(_082_),
    .X(_084_)
  );
  sky130_fd_sc_hd__and4_1 _118_ (
    .A(bit_counter[13]),
    .B(bit_counter[14]),
    .C(bit_counter[15]),
    .D(_082_),
    .X(_085_)
  );
  sky130_fd_sc_hd__and2_0 _119_ (
    .A(bit_counter[16]),
    .B(_085_),
    .X(_086_)
  );
  sky130_fd_sc_hd__and3_1 _120_ (
    .A(bit_counter[16]),
    .B(bit_counter[17]),
    .C(_085_),
    .X(_087_)
  );
  sky130_fd_sc_hd__and4_1 _121_ (
    .A(bit_counter[16]),
    .B(bit_counter[17]),
    .C(bit_counter[18]),
    .D(_085_),
    .X(_088_)
  );
  sky130_fd_sc_hd__and2_0 _122_ (
    .A(bit_counter[19]),
    .B(_088_),
    .X(_089_)
  );
  sky130_fd_sc_hd__and3_1 _123_ (
    .A(bit_counter[19]),
    .B(bit_counter[20]),
    .C(_088_),
    .X(_090_)
  );
  sky130_fd_sc_hd__nand4_1 _124_ (
    .A(bit_counter[19]),
    .B(bit_counter[20]),
    .C(bit_counter[21]),
    .D(_088_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nor2_1 _125_ (
    .A(bit_counter[21]),
    .B(_090_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor4_1 _126_ (
    .A(bit_counter[28]),
    .B(bit_counter[29]),
    .C(bit_counter[30]),
    .D(bit_counter[31]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor4_1 _127_ (
    .A(bit_counter[24]),
    .B(bit_counter[25]),
    .C(bit_counter[26]),
    .D(bit_counter[27]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor4_1 _128_ (
    .A(bit_counter[20]),
    .B(bit_counter[21]),
    .C(bit_counter[22]),
    .D(bit_counter[23]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand3_1 _129_ (
    .A(_093_),
    .B(_094_),
    .C(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand2b_1 _130_ (
    .A_N(bit_counter[3]),
    .B(_074_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nor4_1 _131_ (
    .A(bit_counter[16]),
    .B(bit_counter[17]),
    .C(bit_counter[18]),
    .D(bit_counter[19]),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor4b_1 _132_ (
    .A(bit_counter[13]),
    .B(bit_counter[14]),
    .C(bit_counter[15]),
    .D_N(bit_counter[12]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor4b_1 _133_ (
    .A(bit_counter[8]),
    .B(bit_counter[9]),
    .C(bit_counter[11]),
    .D_N(bit_counter[10]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor4bb_1 _134_ (
    .A(bit_counter[5]),
    .B(bit_counter[7]),
    .C_N(bit_counter[6]),
    .D_N(bit_counter[4]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand4_1 _135_ (
    .A(_098_),
    .B(_099_),
    .C(_100_),
    .D(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor3_1 _136_ (
    .A(_096_),
    .B(_097_),
    .C(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _137_ (
    .A(reset),
    .SLEEP(_103_),
    .X(_033_)
  );
  sky130_fd_sc_hd__nor3b_1 _138_ (
    .A(_033_),
    .B(_092_),
    .C_N(_091_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor2_1 _139_ (
    .A(bit_counter[20]),
    .B(_089_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor3_1 _140_ (
    .A(_090_),
    .B(_033_),
    .C(_034_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor2_1 _141_ (
    .A(bit_counter[19]),
    .B(_088_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nor3_1 _142_ (
    .A(_089_),
    .B(_033_),
    .C(_035_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor2_1 _143_ (
    .A(bit_counter[18]),
    .B(_087_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nor3_1 _144_ (
    .A(_088_),
    .B(_033_),
    .C(_036_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor2_1 _145_ (
    .A(bit_counter[17]),
    .B(_086_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor3_1 _146_ (
    .A(_087_),
    .B(_033_),
    .C(_037_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _147_ (
    .A(bit_counter[16]),
    .B(_085_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor3_1 _148_ (
    .A(_086_),
    .B(_033_),
    .C(_038_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nor2_1 _149_ (
    .A(bit_counter[15]),
    .B(_084_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor3_1 _150_ (
    .A(_085_),
    .B(_033_),
    .C(_039_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _151_ (
    .A(bit_counter[14]),
    .B(_083_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nor3_1 _152_ (
    .A(_084_),
    .B(_033_),
    .C(_040_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _153_ (
    .A(bit_counter[13]),
    .B(_082_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nor3_1 _154_ (
    .A(_083_),
    .B(_033_),
    .C(_041_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nor2_1 _155_ (
    .A(bit_counter[12]),
    .B(_081_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor3_1 _156_ (
    .A(_082_),
    .B(_033_),
    .C(_042_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor2_1 _157_ (
    .A(bit_counter[11]),
    .B(_080_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nor3_1 _158_ (
    .A(_081_),
    .B(_033_),
    .C(_043_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _159_ (
    .A(bit_counter[10]),
    .B(_079_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor3_1 _160_ (
    .A(_080_),
    .B(_033_),
    .C(_044_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor2_1 _161_ (
    .A(bit_counter[9]),
    .B(_078_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nor3_1 _162_ (
    .A(_079_),
    .B(_033_),
    .C(_045_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__a21oi_1 _163_ (
    .A1(bit_counter[7]),
    .A2(_077_),
    .B1(bit_counter[8]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor3_1 _164_ (
    .A(_078_),
    .B(_033_),
    .C(_046_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nor2_1 _165_ (
    .A(bit_counter[7]),
    .B(_077_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a2111oi_0 _166_ (
    .A1(bit_counter[7]),
    .A2(_077_),
    .B1(_103_),
    .C1(_047_),
    .D1(reset),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a21oi_1 _167_ (
    .A1(bit_counter[5]),
    .A2(_076_),
    .B1(bit_counter[6]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor3_1 _168_ (
    .A(_077_),
    .B(_033_),
    .C(_048_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__xnor2_1 _169_ (
    .A(bit_counter[5]),
    .B(_076_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor2_1 _170_ (
    .A(_033_),
    .B(_049_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor2_1 _171_ (
    .A(bit_counter[4]),
    .B(_075_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor3_1 _172_ (
    .A(_076_),
    .B(_033_),
    .C(_050_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__xnor2_1 _173_ (
    .A(bit_counter[3]),
    .B(_074_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor2_1 _174_ (
    .A(_033_),
    .B(_051_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a21oi_1 _175_ (
    .A1(bit_counter[0]),
    .A2(bit_counter[1]),
    .B1(bit_counter[2]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor3_1 _176_ (
    .A(reset),
    .B(_074_),
    .C(_052_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xnor2_1 _177_ (
    .A(bit_counter[0]),
    .B(bit_counter[1]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _178_ (
    .A(_033_),
    .B(_053_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nor2_1 _179_ (
    .A(bit_counter[0]),
    .B(_033_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor2_1 _180_ (
    .A(_071_),
    .B(_091_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor3_1 _181_ (
    .A(_071_),
    .B(_072_),
    .C(_091_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor4_1 _182_ (
    .A(_071_),
    .B(_072_),
    .C(_073_),
    .D(_091_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__and2_0 _183_ (
    .A(bit_counter[25]),
    .B(_056_),
    .X(_057_)
  );
  sky130_fd_sc_hd__and4_1 _184_ (
    .A(bit_counter[25]),
    .B(bit_counter[26]),
    .C(bit_counter[27]),
    .D(_056_),
    .X(_058_)
  );
  sky130_fd_sc_hd__and2_0 _185_ (
    .A(bit_counter[28]),
    .B(_058_),
    .X(_059_)
  );
  sky130_fd_sc_hd__nand4_1 _186_ (
    .A(bit_counter[28]),
    .B(bit_counter[29]),
    .C(bit_counter[30]),
    .D(_058_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a21oi_1 _187_ (
    .A1(bit_counter[29]),
    .A2(_059_),
    .B1(bit_counter[30]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor3b_1 _188_ (
    .A(_061_),
    .B(_033_),
    .C_N(_060_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__a21oi_1 _189_ (
    .A1(bit_counter[29]),
    .A2(_059_),
    .B1(_033_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__o21a_1 _190_ (
    .A1(bit_counter[29]),
    .A2(_059_),
    .B1(_062_),
    .X(_023_)
  );
  sky130_fd_sc_hd__nor2_1 _191_ (
    .A(bit_counter[28]),
    .B(_058_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nor3_1 _192_ (
    .A(_033_),
    .B(_059_),
    .C(_063_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__a21oi_1 _193_ (
    .A1(bit_counter[26]),
    .A2(_057_),
    .B1(bit_counter[27]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor3_1 _194_ (
    .A(_033_),
    .B(_058_),
    .C(_064_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a21oi_1 _195_ (
    .A1(bit_counter[26]),
    .A2(_057_),
    .B1(_033_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__o21a_1 _196_ (
    .A1(bit_counter[26]),
    .A2(_057_),
    .B1(_065_),
    .X(_026_)
  );
  sky130_fd_sc_hd__nor2_1 _197_ (
    .A(bit_counter[25]),
    .B(_056_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nor3_1 _198_ (
    .A(_033_),
    .B(_057_),
    .C(_066_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__xor2_1 _199_ (
    .A(bit_counter[31]),
    .B(_060_),
    .X(_067_)
  );
  sky130_fd_sc_hd__nor2_1 _200_ (
    .A(_033_),
    .B(_067_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _201_ (
    .A(bit_counter[24]),
    .B(_055_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor3_1 _202_ (
    .A(_033_),
    .B(_056_),
    .C(_068_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _203_ (
    .A(_103_),
    .SLEEP(reset),
    .X(_030_)
  );
  sky130_fd_sc_hd__nor2_1 _204_ (
    .A(bit_counter[23]),
    .B(_054_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor3_1 _205_ (
    .A(_033_),
    .B(_055_),
    .C(_069_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a21oi_1 _206_ (
    .A1(bit_counter[21]),
    .A2(_090_),
    .B1(bit_counter[22]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor3_1 _207_ (
    .A(_033_),
    .B(_054_),
    .C(_070_),
    .Y(_032_)
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _208_ (
    .CLK(clk),
    .D(_021_),
    .Q(bit_counter[0])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _209_ (
    .CLK(clk),
    .D(_020_),
    .Q(bit_counter[1])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _210_ (
    .CLK(clk),
    .D(_019_),
    .Q(bit_counter[2])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _211_ (
    .CLK(clk),
    .D(_018_),
    .Q(bit_counter[3])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _212_ (
    .CLK(clk),
    .D(_017_),
    .Q(bit_counter[4])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _213_ (
    .CLK(clk),
    .D(_016_),
    .Q(bit_counter[5])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _214_ (
    .CLK(clk),
    .D(_015_),
    .Q(bit_counter[6])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _215_ (
    .CLK(clk),
    .D(_014_),
    .Q(bit_counter[7])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _216_ (
    .CLK(clk),
    .D(_013_),
    .Q(bit_counter[8])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _217_ (
    .CLK(clk),
    .D(_012_),
    .Q(bit_counter[9])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _218_ (
    .CLK(clk),
    .D(_011_),
    .Q(bit_counter[10])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _219_ (
    .CLK(clk),
    .D(_010_),
    .Q(bit_counter[11])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _220_ (
    .CLK(clk),
    .D(_009_),
    .Q(bit_counter[12])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _221_ (
    .CLK(clk),
    .D(_008_),
    .Q(bit_counter[13])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _222_ (
    .CLK(clk),
    .D(_007_),
    .Q(bit_counter[14])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _223_ (
    .CLK(clk),
    .D(_006_),
    .Q(bit_counter[15])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _224_ (
    .CLK(clk),
    .D(_005_),
    .Q(bit_counter[16])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _225_ (
    .CLK(clk),
    .D(_004_),
    .Q(bit_counter[17])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _226_ (
    .CLK(clk),
    .D(_003_),
    .Q(bit_counter[18])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _227_ (
    .CLK(clk),
    .D(_002_),
    .Q(bit_counter[19])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _228_ (
    .CLK(clk),
    .D(_001_),
    .Q(bit_counter[20])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _229_ (
    .CLK(clk),
    .D(_000_),
    .Q(bit_counter[21])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _230_ (
    .CLK(clk),
    .D(_032_),
    .Q(bit_counter[22])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _231_ (
    .CLK(clk),
    .D(_031_),
    .Q(bit_counter[23])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _232_ (
    .CLK(clk),
    .D(_029_),
    .Q(bit_counter[24])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _233_ (
    .CLK(clk),
    .D(_027_),
    .Q(bit_counter[25])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _234_ (
    .CLK(clk),
    .D(_026_),
    .Q(bit_counter[26])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _235_ (
    .CLK(clk),
    .D(_025_),
    .Q(bit_counter[27])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _236_ (
    .CLK(clk),
    .D(_024_),
    .Q(bit_counter[28])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _237_ (
    .CLK(clk),
    .D(_023_),
    .Q(bit_counter[29])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _238_ (
    .CLK(clk),
    .D(_022_),
    .Q(bit_counter[30])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _239_ (
    .CLK(clk),
    .D(_028_),
    .Q(bit_counter[31])
  );
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  sky130_fd_sc_hd__dfxtp_1 _240_ (
    .CLK(clk),
    .D(_030_),
    .Q(bit_tick)
  );
endmodule

(* hdlname = "uart_rx" *)
(* src = "rtl/uart_rx.v:4.1-235.10" *)
module \$paramod$b7294f1997723f0618629b64f4b039e150234139\uart_rx (clk, reset, rx, rx_data, rx_done, rx_busy);
  (* src = "rtl/uart_rx.v:8.23-8.26" *)
  input clk;
  wire clk;
  (* src = "rtl/uart_rx.v:9.23-9.28" *)
  input reset;
  wire reset;
  (* src = "rtl/uart_rx.v:10.23-10.25" *)
  input rx;
  wire rx;
  (* src = "rtl/uart_rx.v:12.23-12.30" *)
  output [7:0] rx_data;
  wire [7:0] rx_data;
  (* src = "rtl/uart_rx.v:13.23-13.30" *)
  output rx_done;
  wire rx_done;
  (* src = "rtl/uart_rx.v:14.23-14.30" *)
  output rx_busy;
  wire rx_busy;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  (* src = "rtl/uart_rx.v:40.16-40.25" *)
  wire [2:0] bit_count;
  (* src = "rtl/uart_rx.v:39.16-39.25" *)
  wire [15:0] clk_count;
  (* src = "rtl/uart_rx.v:41.16-41.24" *)
  wire [7:0] rx_shift;
  (* onehot = 32'd1 *)
  wire [4:0] state;
  sky130_fd_sc_hd__clkinv_1 _160_ (
    .A(state[1]),
    .Y(_146_)
  );
  sky130_fd_sc_hd__clkinv_1 _161_ (
    .A(clk_count[9]),
    .Y(_147_)
  );
  sky130_fd_sc_hd__clkinv_1 _162_ (
    .A(clk_count[10]),
    .Y(_148_)
  );
  sky130_fd_sc_hd__clkinv_1 _163_ (
    .A(clk_count[15]),
    .Y(_149_)
  );
  sky130_fd_sc_hd__clkinv_1 _164_ (
    .A(bit_count[2]),
    .Y(_150_)
  );
  sky130_fd_sc_hd__clkinv_1 _165_ (
    .A(clk_count[14]),
    .Y(_151_)
  );
  sky130_fd_sc_hd__clkinv_1 _166_ (
    .A(state[2]),
    .Y(_152_)
  );
  sky130_fd_sc_hd__clkinv_1 _167_ (
    .A(rx),
    .Y(_153_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _168_ (
    .A(clk_count[4]),
    .SLEEP(clk_count[3]),
    .X(_154_)
  );
  sky130_fd_sc_hd__nor4b_1 _169_ (
    .A(clk_count[5]),
    .B(clk_count[7]),
    .C(clk_count[9]),
    .D_N(clk_count[6]),
    .Y(_155_)
  );
  sky130_fd_sc_hd__and3_1 _170_ (
    .A(clk_count[1]),
    .B(clk_count[2]),
    .C(clk_count[0]),
    .X(_156_)
  );
  sky130_fd_sc_hd__nor4_1 _171_ (
    .A(clk_count[8]),
    .B(clk_count[13]),
    .C(clk_count[15]),
    .D(clk_count[14]),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand3b_1 _172_ (
    .A_N(clk_count[11]),
    .B(clk_count[12]),
    .C(clk_count[10]),
    .Y(_158_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _173_ (
    .A(_157_),
    .SLEEP(_158_),
    .X(_159_)
  );
  sky130_fd_sc_hd__nand4_1 _174_ (
    .A(_154_),
    .B(_155_),
    .C(_156_),
    .D(_159_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand4_1 _175_ (
    .A(_154_),
    .B(_155_),
    .C(_156_),
    .D(_157_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__o21ai_0 _176_ (
    .A1(_158_),
    .A2(_043_),
    .B1(state[2]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__and2_0 _177_ (
    .A(bit_count[0]),
    .B(bit_count[1]),
    .X(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _178_ (
    .A(bit_count[2]),
    .B(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _179_ (
    .A(state[2]),
    .B(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor4b_1 _180_ (
    .A(clk_count[4]),
    .B(clk_count[6]),
    .C(clk_count[7]),
    .D_N(clk_count[5]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__and4b_1 _181_ (
    .A_N(clk_count[2]),
    .B(clk_count[3]),
    .C(clk_count[0]),
    .D(clk_count[1]),
    .X(_049_)
  );
  sky130_fd_sc_hd__nor4bb_1 _182_ (
    .A(clk_count[10]),
    .B(clk_count[12]),
    .C_N(clk_count[11]),
    .D_N(clk_count[9]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand4_1 _183_ (
    .A(_157_),
    .B(_048_),
    .C(_049_),
    .D(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _184_ (
    .A(state[3]),
    .SLEEP(_051_),
    .X(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _185_ (
    .A(_153_),
    .B(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__a31oi_1 _186_ (
    .A1(_044_),
    .A2(_047_),
    .A3(_053_),
    .B1(reset),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _187_ (
    .A(state[4]),
    .B(rx),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _188_ (
    .A(_042_),
    .B(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor3_1 _189_ (
    .A(reset),
    .B(_042_),
    .C(_054_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor2_1 _190_ (
    .A(state[1]),
    .B(reset),
    .Y(_056_)
  );
  sky130_fd_sc_hd__o21ai_0 _191_ (
    .A1(state[0]),
    .A2(_052_),
    .B1(rx),
    .Y(_057_)
  );
  sky130_fd_sc_hd__or3b_1 _192_ (
    .A(rx),
    .B(_042_),
    .C_N(state[4]),
    .X(_058_)
  );
  sky130_fd_sc_hd__nand3_1 _193_ (
    .A(_056_),
    .B(_057_),
    .C(_058_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _194_ (
    .A(state[4]),
    .B(_042_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor4_1 _195_ (
    .A(_150_),
    .B(_152_),
    .C(_158_),
    .D(_043_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _196_ (
    .A(_045_),
    .B(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__a21oi_1 _197_ (
    .A1(_059_),
    .A2(_061_),
    .B1(reset),
    .Y(_004_)
  );
  sky130_fd_sc_hd__and2_0 _198_ (
    .A(state[3]),
    .B(_051_),
    .X(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(state[3]),
    .B(_051_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a21oi_1 _200_ (
    .A1(_153_),
    .A2(state[0]),
    .B1(_062_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor2_1 _201_ (
    .A(reset),
    .B(_064_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor3_1 _202_ (
    .A(state[2]),
    .B(state[4]),
    .C(state[3]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nor2_1 _203_ (
    .A(reset),
    .B(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nor4_1 _204_ (
    .A(state[1]),
    .B(clk_count[0]),
    .C(reset),
    .D(_065_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor2_1 _205_ (
    .A(_146_),
    .B(reset),
    .Y(_013_)
  );
  sky130_fd_sc_hd__a21o_1 _206_ (
    .A1(clk_count[0]),
    .A2(_013_),
    .B1(_067_),
    .X(_005_)
  );
  sky130_fd_sc_hd__a211oi_1 _207_ (
    .A1(state[3]),
    .A2(rx),
    .B1(state[1]),
    .C1(state[4]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__o2111a_1 _208_ (
    .A1(_152_),
    .A2(_046_),
    .B1(_063_),
    .C1(_068_),
    .D1(_044_),
    .X(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _209_ (
    .A(bit_count[0]),
    .B(bit_count[1]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor3_1 _210_ (
    .A(_152_),
    .B(_045_),
    .C(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__mux2i_1 _211_ (
    .A0(bit_count[1]),
    .A1(_071_),
    .S(_069_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nor2_1 _212_ (
    .A(reset),
    .B(_072_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _213_ (
    .A(bit_count[0]),
    .B(_069_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__o21ai_0 _214_ (
    .A1(bit_count[0]),
    .A2(_152_),
    .B1(_069_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor3b_1 _215_ (
    .A(reset),
    .B(_073_),
    .C_N(_074_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _216_ (
    .A(bit_count[1]),
    .SLEEP(bit_count[0]),
    .X(_075_)
  );
  sky130_fd_sc_hd__a21oi_1 _217_ (
    .A1(_060_),
    .A2(_075_),
    .B1(rx_shift[6]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__and3_1 _218_ (
    .A(_153_),
    .B(_060_),
    .C(_075_),
    .X(_077_)
  );
  sky130_fd_sc_hd__nor3_1 _219_ (
    .A(reset),
    .B(_076_),
    .C(_077_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _220_ (
    .A(bit_count[0]),
    .SLEEP(bit_count[1]),
    .X(_078_)
  );
  sky130_fd_sc_hd__a21oi_1 _221_ (
    .A1(_060_),
    .A2(_078_),
    .B1(rx_shift[5]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__and3_1 _222_ (
    .A(_153_),
    .B(_060_),
    .C(_078_),
    .X(_080_)
  );
  sky130_fd_sc_hd__nor3_1 _223_ (
    .A(reset),
    .B(_079_),
    .C(_080_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a21oi_1 _224_ (
    .A1(_060_),
    .A2(_070_),
    .B1(rx_shift[4]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__and3_1 _225_ (
    .A(_153_),
    .B(_060_),
    .C(_070_),
    .X(_082_)
  );
  sky130_fd_sc_hd__nor3_1 _226_ (
    .A(reset),
    .B(_081_),
    .C(_082_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor4_1 _227_ (
    .A(bit_count[2]),
    .B(_152_),
    .C(_158_),
    .D(_043_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__a21oi_1 _228_ (
    .A1(_045_),
    .A2(_083_),
    .B1(rx_shift[3]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__and3_1 _229_ (
    .A(_153_),
    .B(_045_),
    .C(_083_),
    .X(_085_)
  );
  sky130_fd_sc_hd__nor3_1 _230_ (
    .A(reset),
    .B(_084_),
    .C(_085_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__mux2i_1 _231_ (
    .A0(rx_data[7]),
    .A1(rx_shift[7]),
    .S(_055_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nor2_1 _232_ (
    .A(reset),
    .B(_086_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__a21oi_1 _233_ (
    .A1(_075_),
    .A2(_083_),
    .B1(rx_shift[2]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__and3_1 _234_ (
    .A(_153_),
    .B(_075_),
    .C(_083_),
    .X(_088_)
  );
  sky130_fd_sc_hd__nor3_1 _235_ (
    .A(reset),
    .B(_087_),
    .C(_088_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a21oi_1 _236_ (
    .A1(_078_),
    .A2(_083_),
    .B1(rx_shift[1]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__and3_1 _237_ (
    .A(_153_),
    .B(_078_),
    .C(_083_),
    .X(_090_)
  );
  sky130_fd_sc_hd__nor3_1 _238_ (
    .A(reset),
    .B(_089_),
    .C(_090_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a21oi_1 _239_ (
    .A1(_070_),
    .A2(_083_),
    .B1(rx_shift[0]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__and3_1 _240_ (
    .A(_153_),
    .B(_070_),
    .C(_083_),
    .X(_092_)
  );
  sky130_fd_sc_hd__nor3_1 _241_ (
    .A(reset),
    .B(_091_),
    .C(_092_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__a21oi_1 _242_ (
    .A1(state[3]),
    .A2(_153_),
    .B1(state[2]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2_1 _243_ (
    .A(_054_),
    .B(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__a21oi_1 _244_ (
    .A1(state[4]),
    .A2(_042_),
    .B1(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a21oi_1 _245_ (
    .A1(_063_),
    .A2(_095_),
    .B1(rx_busy),
    .Y(_096_)
  );
  sky130_fd_sc_hd__a211oi_1 _246_ (
    .A1(_064_),
    .A2(_095_),
    .B1(_096_),
    .C1(reset),
    .Y(_017_)
  );
  sky130_fd_sc_hd__and4_1 _247_ (
    .A(clk_count[1]),
    .B(clk_count[2]),
    .C(clk_count[3]),
    .D(clk_count[0]),
    .X(_097_)
  );
  sky130_fd_sc_hd__nand2_1 _248_ (
    .A(clk_count[4]),
    .B(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand4_1 _249_ (
    .A(clk_count[4]),
    .B(clk_count[5]),
    .C(clk_count[6]),
    .D(_097_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _250_ (
    .A(clk_count[7]),
    .B(clk_count[8]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor2_1 _251_ (
    .A(_099_),
    .B(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nor4_1 _252_ (
    .A(_147_),
    .B(_148_),
    .C(_099_),
    .D(_100_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand2_1 _253_ (
    .A(clk_count[11]),
    .B(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand3_1 _254_ (
    .A(clk_count[11]),
    .B(clk_count[12]),
    .C(_102_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand4_1 _255_ (
    .A(clk_count[11]),
    .B(clk_count[12]),
    .C(clk_count[13]),
    .D(_102_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__xnor2_1 _256_ (
    .A(clk_count[14]),
    .B(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a32o_1 _257_ (
    .A1(_146_),
    .A2(_066_),
    .A3(_106_),
    .B1(_013_),
    .B2(clk_count[14]),
    .X(_018_)
  );
  sky130_fd_sc_hd__a21oi_1 _258_ (
    .A1(_045_),
    .A2(_069_),
    .B1(bit_count[2]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__a211oi_1 _259_ (
    .A1(_047_),
    .A2(_069_),
    .B1(_107_),
    .C1(reset),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nor4_1 _260_ (
    .A(state[1]),
    .B(_149_),
    .C(_151_),
    .D(_105_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__o31a_1 _261_ (
    .A1(state[1]),
    .A2(_151_),
    .A3(_105_),
    .B1(_149_),
    .X(_109_)
  );
  sky130_fd_sc_hd__nor2_1 _262_ (
    .A(_066_),
    .B(_013_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nor3_1 _263_ (
    .A(_108_),
    .B(_109_),
    .C(_110_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__a41oi_1 _264_ (
    .A1(_146_),
    .A2(clk_count[11]),
    .A3(clk_count[12]),
    .A4(_102_),
    .B1(clk_count[13]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a21oi_1 _265_ (
    .A1(_066_),
    .A2(_105_),
    .B1(_013_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nor2_1 _266_ (
    .A(_111_),
    .B(_112_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2b_1 _267_ (
    .A_N(clk_count[12]),
    .B(_103_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__o21a_1 _268_ (
    .A1(state[2]),
    .A2(state[4]),
    .B1(_042_),
    .X(_114_)
  );
  sky130_fd_sc_hd__o21a_1 _269_ (
    .A1(state[3]),
    .A2(_114_),
    .B1(_056_),
    .X(_115_)
  );
  sky130_fd_sc_hd__a32o_1 _270_ (
    .A1(_104_),
    .A2(_113_),
    .A3(_115_),
    .B1(_013_),
    .B2(clk_count[12]),
    .X(_022_)
  );
  sky130_fd_sc_hd__nor2_1 _271_ (
    .A(clk_count[11]),
    .B(_102_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__o31ai_1 _272_ (
    .A1(state[2]),
    .A2(state[4]),
    .A3(_062_),
    .B1(_056_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nor2_1 _273_ (
    .A(_116_),
    .B(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__a22o_1 _274_ (
    .A1(clk_count[11]),
    .A2(_013_),
    .B1(_103_),
    .B2(_118_),
    .X(_023_)
  );
  sky130_fd_sc_hd__a21oi_1 _275_ (
    .A1(clk_count[9]),
    .A2(_101_),
    .B1(clk_count[10]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nor2_1 _276_ (
    .A(_102_),
    .B(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__a22o_1 _277_ (
    .A1(clk_count[10]),
    .A2(_013_),
    .B1(_115_),
    .B2(_120_),
    .X(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _278_ (
    .A(clk_count[9]),
    .B(_013_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__xnor2_1 _279_ (
    .A(clk_count[9]),
    .B(_101_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__o21ai_0 _280_ (
    .A1(_117_),
    .A2(_122_),
    .B1(_121_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nor2_1 _281_ (
    .A(state[1]),
    .B(_099_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a21oi_1 _282_ (
    .A1(clk_count[7]),
    .A2(_123_),
    .B1(clk_count[8]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__a311oi_1 _283_ (
    .A1(clk_count[7]),
    .A2(clk_count[8]),
    .A3(_123_),
    .B1(_124_),
    .C1(_110_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor2_1 _284_ (
    .A(clk_count[7]),
    .B(_123_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a211oi_1 _285_ (
    .A1(clk_count[7]),
    .A2(_123_),
    .B1(_125_),
    .C1(_110_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a31o_1 _286_ (
    .A1(clk_count[4]),
    .A2(clk_count[5]),
    .A3(_097_),
    .B1(clk_count[6]),
    .X(_126_)
  );
  sky130_fd_sc_hd__a32o_1 _287_ (
    .A1(_099_),
    .A2(_115_),
    .A3(_126_),
    .B1(_013_),
    .B2(clk_count[6]),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2i_1 _288_ (
    .A0(rx_data[6]),
    .A1(rx_shift[6]),
    .S(_055_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nor2_1 _289_ (
    .A(reset),
    .B(_127_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__mux2i_1 _290_ (
    .A0(rx_data[5]),
    .A1(rx_shift[5]),
    .S(_055_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nor2_1 _291_ (
    .A(reset),
    .B(_128_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__mux2i_1 _292_ (
    .A0(rx_data[4]),
    .A1(rx_shift[4]),
    .S(_055_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nor2_1 _293_ (
    .A(reset),
    .B(_129_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__mux2i_1 _294_ (
    .A0(rx_data[3]),
    .A1(rx_shift[3]),
    .S(_055_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nor2_1 _295_ (
    .A(reset),
    .B(_130_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__mux2i_1 _296_ (
    .A0(rx_data[2]),
    .A1(rx_shift[2]),
    .S(_055_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nor2_1 _297_ (
    .A(reset),
    .B(_131_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__mux2i_1 _298_ (
    .A0(rx_data[1]),
    .A1(rx_shift[1]),
    .S(_055_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor2_1 _299_ (
    .A(reset),
    .B(_132_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__mux2i_1 _300_ (
    .A0(rx_data[0]),
    .A1(rx_shift[0]),
    .S(_055_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nor2_1 _301_ (
    .A(reset),
    .B(_133_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _302_ (
    .A(clk_count[5]),
    .B(_013_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__xor2_1 _303_ (
    .A(clk_count[5]),
    .B(_098_),
    .X(_135_)
  );
  sky130_fd_sc_hd__o21ai_0 _304_ (
    .A1(_117_),
    .A2(_135_),
    .B1(_134_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _305_ (
    .A(clk_count[4]),
    .SLEEP(_097_),
    .X(_136_)
  );
  sky130_fd_sc_hd__a32o_1 _306_ (
    .A1(_098_),
    .A2(_115_),
    .A3(_136_),
    .B1(_013_),
    .B2(clk_count[4]),
    .X(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _307_ (
    .A(clk_count[3]),
    .B(_013_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nor3_1 _308_ (
    .A(state[1]),
    .B(reset),
    .C(_097_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__o221ai_1 _309_ (
    .A1(clk_count[3]),
    .A2(_156_),
    .B1(_062_),
    .B2(_114_),
    .C1(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nand2_1 _310_ (
    .A(_137_),
    .B(_139_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _311_ (
    .A1(_045_),
    .A2(_060_),
    .B1(rx_shift[7]),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nor2_1 _312_ (
    .A(rx),
    .B(_061_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nor3_1 _313_ (
    .A(reset),
    .B(_140_),
    .C(_141_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a21oi_1 _314_ (
    .A1(clk_count[1]),
    .A2(clk_count[0]),
    .B1(clk_count[2]),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand2_1 _315_ (
    .A(clk_count[2]),
    .B(_013_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__o31ai_1 _316_ (
    .A1(_156_),
    .A2(_117_),
    .A3(_142_),
    .B1(_143_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a21oi_1 _317_ (
    .A1(_146_),
    .A2(clk_count[0]),
    .B1(clk_count[1]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__and3_1 _318_ (
    .A(clk_count[1]),
    .B(_146_),
    .C(clk_count[0]),
    .X(_145_)
  );
  sky130_fd_sc_hd__nor3_1 _319_ (
    .A(_110_),
    .B(_144_),
    .C(_145_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__dfxtp_1 _320_ (
    .CLK(clk),
    .D(_001_),
    .Q(state[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _321_ (
    .CLK(clk),
    .D(_000_),
    .Q(state[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _322_ (
    .CLK(clk),
    .D(_002_),
    .Q(state[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _323_ (
    .CLK(clk),
    .D(_003_),
    .Q(state[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _324_ (
    .CLK(clk),
    .D(_004_),
    .Q(state[4])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _325_ (
    .CLK(clk),
    .D(_035_),
    .Q(rx_data[0])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _326_ (
    .CLK(clk),
    .D(_034_),
    .Q(rx_data[1])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _327_ (
    .CLK(clk),
    .D(_033_),
    .Q(rx_data[2])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _328_ (
    .CLK(clk),
    .D(_032_),
    .Q(rx_data[3])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _329_ (
    .CLK(clk),
    .D(_031_),
    .Q(rx_data[4])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _330_ (
    .CLK(clk),
    .D(_030_),
    .Q(rx_data[5])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _331_ (
    .CLK(clk),
    .D(_029_),
    .Q(rx_data[6])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _332_ (
    .CLK(clk),
    .D(_012_),
    .Q(rx_data[7])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _333_ (
    .CLK(clk),
    .D(_013_),
    .Q(rx_done)
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _334_ (
    .CLK(clk),
    .D(_017_),
    .Q(rx_busy)
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _335_ (
    .CLK(clk),
    .D(_007_),
    .Q(bit_count[0])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _336_ (
    .CLK(clk),
    .D(_006_),
    .Q(bit_count[1])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _337_ (
    .CLK(clk),
    .D(_019_),
    .Q(bit_count[2])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _338_ (
    .CLK(clk),
    .D(_005_),
    .Q(clk_count[0])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _339_ (
    .CLK(clk),
    .D(_041_),
    .Q(clk_count[1])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _340_ (
    .CLK(clk),
    .D(_040_),
    .Q(clk_count[2])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _341_ (
    .CLK(clk),
    .D(_038_),
    .Q(clk_count[3])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _342_ (
    .CLK(clk),
    .D(_037_),
    .Q(clk_count[4])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _343_ (
    .CLK(clk),
    .D(_036_),
    .Q(clk_count[5])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _344_ (
    .CLK(clk),
    .D(_028_),
    .Q(clk_count[6])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _345_ (
    .CLK(clk),
    .D(_027_),
    .Q(clk_count[7])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _346_ (
    .CLK(clk),
    .D(_026_),
    .Q(clk_count[8])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _347_ (
    .CLK(clk),
    .D(_025_),
    .Q(clk_count[9])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _348_ (
    .CLK(clk),
    .D(_024_),
    .Q(clk_count[10])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _349_ (
    .CLK(clk),
    .D(_023_),
    .Q(clk_count[11])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _350_ (
    .CLK(clk),
    .D(_022_),
    .Q(clk_count[12])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _351_ (
    .CLK(clk),
    .D(_021_),
    .Q(clk_count[13])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _352_ (
    .CLK(clk),
    .D(_018_),
    .Q(clk_count[14])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _353_ (
    .CLK(clk),
    .D(_020_),
    .Q(clk_count[15])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _354_ (
    .CLK(clk),
    .D(_016_),
    .Q(rx_shift[0])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _355_ (
    .CLK(clk),
    .D(_015_),
    .Q(rx_shift[1])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _356_ (
    .CLK(clk),
    .D(_014_),
    .Q(rx_shift[2])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _357_ (
    .CLK(clk),
    .D(_011_),
    .Q(rx_shift[3])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _358_ (
    .CLK(clk),
    .D(_010_),
    .Q(rx_shift[4])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _359_ (
    .CLK(clk),
    .D(_009_),
    .Q(rx_shift[5])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _360_ (
    .CLK(clk),
    .D(_008_),
    .Q(rx_shift[6])
  );
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  sky130_fd_sc_hd__dfxtp_1 _361_ (
    .CLK(clk),
    .D(_039_),
    .Q(rx_shift[7])
  );
endmodule

(* top =  1  *)
(* src = "rtl/uart_top.v:4.1-78.10" *)
module uart_top(clk, reset, tx_start, tx_data, tx, tx_busy, tx_done, rx, rx_data, rx_done, rx_busy);
  (* src = "rtl/uart_top.v:8.23-8.26" *)
  input clk;
  wire clk;
  (* src = "rtl/uart_top.v:9.23-9.28" *)
  input reset;
  wire reset;
  (* src = "rtl/uart_top.v:12.23-12.31" *)
  input tx_start;
  wire tx_start;
  (* src = "rtl/uart_top.v:13.23-13.30" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "rtl/uart_top.v:14.23-14.25" *)
  output tx;
  wire tx;
  (* src = "rtl/uart_top.v:15.23-15.30" *)
  output tx_busy;
  wire tx_busy;
  (* src = "rtl/uart_top.v:16.23-16.30" *)
  output tx_done;
  wire tx_done;
  (* src = "rtl/uart_top.v:19.23-19.25" *)
  input rx;
  wire rx;
  (* src = "rtl/uart_top.v:20.23-20.30" *)
  output [7:0] rx_data;
  wire [7:0] rx_data;
  (* src = "rtl/uart_top.v:21.23-21.30" *)
  output rx_done;
  wire rx_done;
  (* src = "rtl/uart_top.v:22.23-22.30" *)
  output rx_busy;
  wire rx_busy;
  (* src = "rtl/uart_top.v:29.10-29.18" *)
  wire bit_tick;
  (* src = "rtl/uart_top.v:39.7-43.6" *)
  \$paramod$b7294f1997723f0618629b64f4b039e150234139\baud_tick_gen  baud_gen_inst (
    .bit_tick(bit_tick),
    .clk(clk),
    .reset(reset)
  );
  (* src = "rtl/uart_top.v:69.7-76.6" *)
  \$paramod$b7294f1997723f0618629b64f4b039e150234139\uart_rx  rx_inst (
    .clk(clk),
    .reset(reset),
    .rx(rx),
    .rx_busy(rx_busy),
    .rx_data(rx_data),
    .rx_done(rx_done)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/uart_top.v:50.13-59.6" *)
  uart_tx tx_inst (
    .bit_tick(bit_tick),
    .clk(clk),
    .reset(reset),
    .tx(tx),
    .tx_busy(tx_busy),
    .tx_data(tx_data),
    .tx_done(tx_done),
    .tx_start(tx_start)
  );
endmodule

(* src = "rtl/uart_tx.v:4.1-195.10" *)
module uart_tx(clk, reset, tx_start, tx_data, bit_tick, tx, tx_busy, tx_done);
  (* src = "rtl/uart_tx.v:8.23-8.26" *)
  input clk;
  wire clk;
  (* src = "rtl/uart_tx.v:9.23-9.28" *)
  input reset;
  wire reset;
  (* src = "rtl/uart_tx.v:11.23-11.31" *)
  input tx_start;
  wire tx_start;
  (* src = "rtl/uart_tx.v:12.23-12.30" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "rtl/uart_tx.v:14.23-14.31" *)
  input bit_tick;
  wire bit_tick;
  (* src = "rtl/uart_tx.v:16.23-16.25" *)
  output tx;
  wire tx;
  (* src = "rtl/uart_tx.v:17.23-17.30" *)
  output tx_busy;
  wire tx_busy;
  (* src = "rtl/uart_tx.v:18.23-18.30" *)
  output tx_done;
  wire tx_done;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  (* src = "rtl/uart_tx.v:39.15-39.24" *)
  wire [2:0] bit_count;
  (* onehot = 32'd1 *)
  wire [3:0] state;
  (* src = "rtl/uart_tx.v:37.15-37.27" *)
  wire [7:0] tx_shift_reg;
  sky130_fd_sc_hd__clkinv_1 _058_ (
    .A(tx_start),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _059_ (
    .A(state[1]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _060_ (
    .A(bit_tick),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor2_1 _061_ (
    .A(reset),
    .B(bit_tick),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _062_ (
    .A(state[1]),
    .B(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _063_ (
    .A(bit_count[1]),
    .B(bit_count[0]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand3_1 _064_ (
    .A(bit_count[1]),
    .B(bit_count[0]),
    .C(bit_count[2]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2b_1 _065_ (
    .A_N(reset),
    .B(bit_tick),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor2_1 _066_ (
    .A(state[1]),
    .B(state[2]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a21oi_1 _067_ (
    .A1(state[1]),
    .A2(_025_),
    .B1(state[2]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__o21ai_0 _068_ (
    .A1(_026_),
    .A2(_028_),
    .B1(_023_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _069_ (
    .A(bit_tick),
    .B(state[3]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a21oi_1 _070_ (
    .A1(_019_),
    .A2(state[0]),
    .B1(reset),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _071_ (
    .A(_029_),
    .B(_030_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2b_1 _072_ (
    .A_N(bit_tick),
    .B(state[2]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _073_ (
    .A(tx_start),
    .B(state[0]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a21oi_1 _074_ (
    .A1(_031_),
    .A2(_032_),
    .B1(reset),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _075_ (
    .A(state[3]),
    .B(_022_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__o31ai_1 _076_ (
    .A1(_020_),
    .A2(_025_),
    .A3(_026_),
    .B1(_033_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__a21o_1 _077_ (
    .A1(bit_tick),
    .A2(_025_),
    .B1(_020_),
    .X(_034_)
  );
  sky130_fd_sc_hd__o21ai_0 _078_ (
    .A1(_020_),
    .A2(state[0]),
    .B1(_032_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _079_ (
    .A(_020_),
    .B(tx_data[7]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__a21oi_1 _080_ (
    .A1(_034_),
    .A2(_035_),
    .B1(tx_shift_reg[7]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a311oi_1 _081_ (
    .A1(_034_),
    .A2(_035_),
    .A3(_036_),
    .B1(_037_),
    .C1(reset),
    .Y(_004_)
  );
  sky130_fd_sc_hd__mux2i_1 _082_ (
    .A0(tx_data[4]),
    .A1(tx_shift_reg[5]),
    .S(state[1]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _083_ (
    .A1(_034_),
    .A2(_035_),
    .B1(tx_shift_reg[4]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a311oi_1 _084_ (
    .A1(_034_),
    .A2(_035_),
    .A3(_038_),
    .B1(_039_),
    .C1(reset),
    .Y(_005_)
  );
  sky130_fd_sc_hd__mux2i_1 _085_ (
    .A0(tx_data[3]),
    .A1(tx_shift_reg[4]),
    .S(state[1]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a21oi_1 _086_ (
    .A1(_034_),
    .A2(_035_),
    .B1(tx_shift_reg[3]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__a311oi_1 _087_ (
    .A1(_034_),
    .A2(_035_),
    .A3(_040_),
    .B1(_041_),
    .C1(reset),
    .Y(_006_)
  );
  sky130_fd_sc_hd__mux2i_1 _088_ (
    .A0(tx_data[2]),
    .A1(tx_shift_reg[3]),
    .S(state[1]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a21oi_1 _089_ (
    .A1(_034_),
    .A2(_035_),
    .B1(tx_shift_reg[2]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a311oi_1 _090_ (
    .A1(_034_),
    .A2(_035_),
    .A3(_042_),
    .B1(_043_),
    .C1(reset),
    .Y(_007_)
  );
  sky130_fd_sc_hd__mux2i_1 _091_ (
    .A0(tx_data[1]),
    .A1(tx_shift_reg[2]),
    .S(state[1]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__a21oi_1 _092_ (
    .A1(_034_),
    .A2(_035_),
    .B1(tx_shift_reg[1]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a311oi_1 _093_ (
    .A1(_034_),
    .A2(_035_),
    .A3(_044_),
    .B1(_045_),
    .C1(reset),
    .Y(_008_)
  );
  sky130_fd_sc_hd__o31a_1 _094_ (
    .A1(state[1]),
    .A2(state[2]),
    .A3(state[0]),
    .B1(_031_),
    .X(_046_)
  );
  sky130_fd_sc_hd__and2_0 _095_ (
    .A(_034_),
    .B(_046_),
    .X(_047_)
  );
  sky130_fd_sc_hd__a41oi_1 _096_ (
    .A1(bit_count[1]),
    .A2(bit_count[0]),
    .A3(_034_),
    .A4(_046_),
    .B1(bit_count[2]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a211oi_1 _097_ (
    .A1(_020_),
    .A2(_046_),
    .B1(_048_),
    .C1(reset),
    .Y(_009_)
  );
  sky130_fd_sc_hd__mux2i_1 _098_ (
    .A0(tx_data[0]),
    .A1(tx_shift_reg[1]),
    .S(state[1]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__a21oi_1 _099_ (
    .A1(_034_),
    .A2(_035_),
    .B1(tx_shift_reg[0]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a311oi_1 _100_ (
    .A1(_034_),
    .A2(_035_),
    .A3(_049_),
    .B1(_050_),
    .C1(reset),
    .Y(_010_)
  );
  sky130_fd_sc_hd__a21oi_1 _101_ (
    .A1(state[1]),
    .A2(bit_tick),
    .B1(bit_count[0]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a211oi_1 _102_ (
    .A1(bit_count[0]),
    .A2(_047_),
    .B1(_051_),
    .C1(reset),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor2_1 _103_ (
    .A(reset),
    .B(_029_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__o21ai_0 _104_ (
    .A1(_021_),
    .A2(state[0]),
    .B1(_030_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__o21ai_0 _105_ (
    .A1(reset),
    .A2(_027_),
    .B1(_052_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__a31oi_1 _106_ (
    .A1(bit_count[0]),
    .A2(_034_),
    .A3(_046_),
    .B1(bit_count[1]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _107_ (
    .A(state[1]),
    .B(_024_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a211oi_1 _108_ (
    .A1(_047_),
    .A2(_054_),
    .B1(_053_),
    .C1(reset),
    .Y(_014_)
  );
  sky130_fd_sc_hd__mux2i_1 _109_ (
    .A0(tx_data[6]),
    .A1(tx_shift_reg[7]),
    .S(state[1]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__a21oi_1 _110_ (
    .A1(_034_),
    .A2(_035_),
    .B1(tx_shift_reg[6]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__a311oi_1 _111_ (
    .A1(_034_),
    .A2(_035_),
    .A3(_055_),
    .B1(_056_),
    .C1(reset),
    .Y(_015_)
  );
  sky130_fd_sc_hd__mux2i_1 _112_ (
    .A0(tx_data[5]),
    .A1(tx_shift_reg[6]),
    .S(state[1]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a21oi_1 _113_ (
    .A1(_034_),
    .A2(_035_),
    .B1(tx_shift_reg[5]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a311oi_1 _114_ (
    .A1(_034_),
    .A2(_035_),
    .A3(_057_),
    .B1(_018_),
    .C1(reset),
    .Y(_016_)
  );
  sky130_fd_sc_hd__a211o_1 _115_ (
    .A1(tx_shift_reg[0]),
    .A2(state[1]),
    .B1(reset),
    .C1(_027_),
    .X(_017_)
  );
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  sky130_fd_sc_hd__dfxtp_1 _116_ (
    .CLK(clk),
    .D(_017_),
    .Q(tx)
  );
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  sky130_fd_sc_hd__dfxtp_1 _117_ (
    .CLK(clk),
    .D(_012_),
    .Q(tx_done)
  );
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  sky130_fd_sc_hd__dfxtp_1 _118_ (
    .CLK(clk),
    .D(_013_),
    .Q(tx_busy)
  );
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  sky130_fd_sc_hd__dfxtp_1 _119_ (
    .CLK(clk),
    .D(_010_),
    .Q(tx_shift_reg[0])
  );
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  sky130_fd_sc_hd__dfxtp_1 _120_ (
    .CLK(clk),
    .D(_008_),
    .Q(tx_shift_reg[1])
  );
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  sky130_fd_sc_hd__dfxtp_1 _121_ (
    .CLK(clk),
    .D(_007_),
    .Q(tx_shift_reg[2])
  );
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  sky130_fd_sc_hd__dfxtp_1 _122_ (
    .CLK(clk),
    .D(_006_),
    .Q(tx_shift_reg[3])
  );
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  sky130_fd_sc_hd__dfxtp_1 _123_ (
    .CLK(clk),
    .D(_005_),
    .Q(tx_shift_reg[4])
  );
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  sky130_fd_sc_hd__dfxtp_1 _124_ (
    .CLK(clk),
    .D(_016_),
    .Q(tx_shift_reg[5])
  );
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  sky130_fd_sc_hd__dfxtp_1 _125_ (
    .CLK(clk),
    .D(_015_),
    .Q(tx_shift_reg[6])
  );
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  sky130_fd_sc_hd__dfxtp_1 _126_ (
    .CLK(clk),
    .D(_004_),
    .Q(tx_shift_reg[7])
  );
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  sky130_fd_sc_hd__dfxtp_1 _127_ (
    .CLK(clk),
    .D(_011_),
    .Q(bit_count[0])
  );
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  sky130_fd_sc_hd__dfxtp_1 _128_ (
    .CLK(clk),
    .D(_014_),
    .Q(bit_count[1])
  );
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  sky130_fd_sc_hd__dfxtp_1 _129_ (
    .CLK(clk),
    .D(_009_),
    .Q(bit_count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _130_ (
    .CLK(clk),
    .D(_000_),
    .Q(state[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _131_ (
    .CLK(clk),
    .D(_001_),
    .Q(state[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _132_ (
    .CLK(clk),
    .D(_002_),
    .Q(state[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _133_ (
    .CLK(clk),
    .D(_003_),
    .Q(state[3])
  );
endmodule
