/* Generated by Yosys 0.68+136 (git sha1 c30457480-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

(* hdlname = "baud_tick_gen" *)
(* src = "rtl/baud_tick_gen.v:4.1-63.10" *)
module \$paramod$b7294f1997723f0618629b64f4b039e150234139\baud_tick_gen (clk, reset, bit_tick);
  (* src = "rtl/baud_tick_gen.v:8.17-8.20" *)
  input clk;
  wire clk;
  (* src = "rtl/baud_tick_gen.v:9.17-9.22" *)
  input reset;
  wire reset;
  (* src = "rtl/baud_tick_gen.v:11.17-11.25" *)
  output bit_tick;
  reg bit_tick;
  wire _000_;
  (* src = "rtl/baud_tick_gen.v:46.17-46.48" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/baud_tick_gen.v:55.32-55.50|C:\\Users\\rkp77\\oss-cad-suite\\bin\\../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _060_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/baud_tick_gen.v:55.32-55.50|C:\\Users\\rkp77\\oss-cad-suite\\bin\\../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _061_;
  (* src = "rtl/baud_tick_gen.v:25.16-25.27" *)
  reg [31:0] bit_counter;
  assign _060_[0] = ~bit_counter[0];
  assign _030_ = bit_counter[1] & bit_counter[0];
  assign _031_ = bit_counter[2] & _030_;
  assign _032_ = bit_counter[3] & _031_;
  assign _033_ = bit_counter[4] & _032_;
  assign _034_ = bit_counter[5] & _033_;
  assign _035_ = bit_counter[6] & _034_;
  assign _036_ = bit_counter[7] & _035_;
  assign _037_ = bit_counter[8] & _036_;
  assign _038_ = bit_counter[9] & _037_;
  assign _039_ = bit_counter[10] & _038_;
  assign _040_ = bit_counter[11] & _039_;
  assign _041_ = bit_counter[12] & _040_;
  assign _042_ = bit_counter[13] & _041_;
  assign _043_ = bit_counter[14] & _042_;
  assign _044_ = bit_counter[15] & _043_;
  assign _045_ = bit_counter[16] & _044_;
  assign _046_ = bit_counter[17] & _045_;
  assign _047_ = bit_counter[18] & _046_;
  assign _048_ = bit_counter[19] & _047_;
  assign _049_ = bit_counter[20] & _048_;
  assign _050_ = bit_counter[21] & _049_;
  assign _051_ = bit_counter[22] & _050_;
  assign _052_ = bit_counter[23] & _051_;
  assign _053_ = bit_counter[24] & _052_;
  assign _054_ = bit_counter[25] & _053_;
  assign _055_ = bit_counter[26] & _054_;
  assign _056_ = bit_counter[27] & _055_;
  assign _057_ = bit_counter[28] & _056_;
  assign _058_ = bit_counter[29] & _057_;
  assign _059_ = ~(bit_counter[30] & _058_);
  assign _061_[31] = ~(bit_counter[31] ^ _059_);
  assign _061_[30] = bit_counter[30] ^ _058_;
  assign _061_[29] = bit_counter[29] ^ _057_;
  assign _061_[28] = bit_counter[28] ^ _056_;
  assign _061_[27] = bit_counter[27] ^ _055_;
  assign _061_[26] = bit_counter[26] ^ _054_;
  assign _061_[25] = bit_counter[25] ^ _053_;
  assign _061_[24] = bit_counter[24] ^ _052_;
  assign _061_[23] = bit_counter[23] ^ _051_;
  assign _061_[22] = bit_counter[22] ^ _050_;
  assign _061_[21] = bit_counter[21] ^ _049_;
  assign _061_[20] = bit_counter[20] ^ _048_;
  assign _061_[19] = bit_counter[19] ^ _047_;
  assign _061_[18] = bit_counter[18] ^ _046_;
  assign _061_[17] = bit_counter[17] ^ _045_;
  assign _061_[16] = bit_counter[16] ^ _044_;
  assign _061_[15] = bit_counter[15] ^ _043_;
  assign _061_[14] = bit_counter[14] ^ _042_;
  assign _061_[13] = bit_counter[13] ^ _041_;
  assign _061_[12] = bit_counter[12] ^ _040_;
  assign _061_[11] = bit_counter[11] ^ _039_;
  assign _061_[10] = bit_counter[10] ^ _038_;
  assign _061_[9] = bit_counter[9] ^ _037_;
  assign _061_[8] = bit_counter[8] ^ _036_;
  assign _061_[7] = bit_counter[7] ^ _035_;
  assign _061_[6] = bit_counter[6] ^ _034_;
  assign _061_[5] = bit_counter[5] ^ _033_;
  assign _061_[4] = bit_counter[4] ^ _032_;
  assign _002_ = _031_ & ~(bit_counter[3]);
  assign _061_[3] = bit_counter[3] ^ _031_;
  assign _061_[2] = bit_counter[2] ^ _030_;
  assign _061_[1] = bit_counter[1] ^ bit_counter[0];
  assign _003_ = ~(bit_counter[14] | bit_counter[13]);
  assign _004_ = bit_counter[12] & ~(bit_counter[7]);
  assign _005_ = _003_ & _004_;
  assign _006_ = ~(bit_counter[19] | bit_counter[17]);
  assign _007_ = ~(bit_counter[16] | bit_counter[15]);
  assign _008_ = _006_ & _007_;
  assign _009_ = ~(bit_counter[25] | bit_counter[23]);
  assign _010_ = ~(bit_counter[22] | bit_counter[21]);
  assign _011_ = _009_ & _010_;
  assign _012_ = _008_ & _011_;
  assign _013_ = _005_ & _012_;
  assign _014_ = bit_counter[4] & ~(bit_counter[20]);
  assign _015_ = bit_counter[6] & ~(bit_counter[24]);
  assign _016_ = _014_ & _015_;
  assign _017_ = ~(bit_counter[29] | bit_counter[28]);
  assign _018_ = ~(bit_counter[9] | bit_counter[8]);
  assign _019_ = _017_ & _018_;
  assign _020_ = _016_ & _019_;
  assign _021_ = ~(bit_counter[31] | bit_counter[30]);
  assign _022_ = ~(bit_counter[27] | bit_counter[26]);
  assign _023_ = _021_ & _022_;
  assign _024_ = bit_counter[10] & ~(bit_counter[18]);
  assign _025_ = ~(bit_counter[5] | bit_counter[11]);
  assign _026_ = _024_ & _025_;
  assign _027_ = _023_ & _026_;
  assign _028_ = _020_ & _027_;
  assign _029_ = _002_ & _028_;
  assign _001_ = _013_ & _029_;
  assign _000_ = reset | _001_;
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[0] <= 1'h0;
    else bit_counter[0] <= _060_[0];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[1] <= 1'h0;
    else bit_counter[1] <= _061_[1];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[2] <= 1'h0;
    else bit_counter[2] <= _061_[2];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[3] <= 1'h0;
    else bit_counter[3] <= _061_[3];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[4] <= 1'h0;
    else bit_counter[4] <= _061_[4];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[5] <= 1'h0;
    else bit_counter[5] <= _061_[5];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[6] <= 1'h0;
    else bit_counter[6] <= _061_[6];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[7] <= 1'h0;
    else bit_counter[7] <= _061_[7];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[8] <= 1'h0;
    else bit_counter[8] <= _061_[8];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[9] <= 1'h0;
    else bit_counter[9] <= _061_[9];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[10] <= 1'h0;
    else bit_counter[10] <= _061_[10];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[11] <= 1'h0;
    else bit_counter[11] <= _061_[11];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[12] <= 1'h0;
    else bit_counter[12] <= _061_[12];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[13] <= 1'h0;
    else bit_counter[13] <= _061_[13];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[14] <= 1'h0;
    else bit_counter[14] <= _061_[14];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[15] <= 1'h0;
    else bit_counter[15] <= _061_[15];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[16] <= 1'h0;
    else bit_counter[16] <= _061_[16];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[17] <= 1'h0;
    else bit_counter[17] <= _061_[17];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[18] <= 1'h0;
    else bit_counter[18] <= _061_[18];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[19] <= 1'h0;
    else bit_counter[19] <= _061_[19];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[20] <= 1'h0;
    else bit_counter[20] <= _061_[20];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[21] <= 1'h0;
    else bit_counter[21] <= _061_[21];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[22] <= 1'h0;
    else bit_counter[22] <= _061_[22];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[23] <= 1'h0;
    else bit_counter[23] <= _061_[23];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[24] <= 1'h0;
    else bit_counter[24] <= _061_[24];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[25] <= 1'h0;
    else bit_counter[25] <= _061_[25];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[26] <= 1'h0;
    else bit_counter[26] <= _061_[26];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[27] <= 1'h0;
    else bit_counter[27] <= _061_[27];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[28] <= 1'h0;
    else bit_counter[28] <= _061_[28];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[29] <= 1'h0;
    else bit_counter[29] <= _061_[29];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[30] <= 1'h0;
    else bit_counter[30] <= _061_[30];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (_000_) bit_counter[31] <= 1'h0;
    else bit_counter[31] <= _061_[31];
  (* src = "rtl/baud_tick_gen.v:32.5-61.8" *)
  always @(posedge clk)
    if (reset) bit_tick <= 1'h0;
    else bit_tick <= _001_;
  assign _061_[0] = _060_[0];
  assign _060_[31:1] = bit_counter[31:1];
endmodule

(* hdlname = "uart_rx" *)
(* src = "rtl/uart_rx.v:4.1-235.10" *)
module \$paramod$b7294f1997723f0618629b64f4b039e150234139\uart_rx (clk, reset, rx, rx_data, rx_done, rx_busy);
  (* src = "rtl/uart_rx.v:8.23-8.26" *)
  input clk;
  wire clk;
  (* src = "rtl/uart_rx.v:9.23-9.28" *)
  input reset;
  wire reset;
  (* src = "rtl/uart_rx.v:10.23-10.25" *)
  input rx;
  wire rx;
  (* src = "rtl/uart_rx.v:12.23-12.30" *)
  output [7:0] rx_data;
  reg [7:0] rx_data;
  (* src = "rtl/uart_rx.v:13.23-13.30" *)
  output rx_done;
  reg rx_done;
  (* src = "rtl/uart_rx.v:14.23-14.30" *)
  output rx_busy;
  reg rx_busy;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  (* src = "rtl/uart_rx.v:142.25-142.50" *)
  wire _118_;
  (* src = "rtl/uart_rx.v:142.25-142.50" *)
  wire _119_;
  (* src = "rtl/uart_rx.v:142.25-142.50" *)
  wire _120_;
  (* src = "rtl/uart_rx.v:142.25-142.50" *)
  wire _121_;
  (* src = "rtl/uart_rx.v:142.25-142.50" *)
  wire _122_;
  (* src = "rtl/uart_rx.v:142.25-142.50" *)
  wire _123_;
  (* src = "rtl/uart_rx.v:142.25-142.50" *)
  wire _124_;
  (* src = "rtl/uart_rx.v:142.25-142.50" *)
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  (* src = "rtl/uart_rx.v:40.16-40.25" *)
  reg [2:0] bit_count;
  (* src = "rtl/uart_rx.v:39.16-39.25" *)
  reg [15:0] clk_count;
  (* src = "rtl/uart_rx.v:41.16-41.24" *)
  reg [7:0] rx_shift;
  (* onehot = 32'd1 *)
  reg [4:0] state;
  assign _092_ = ~clk_count[0];
  assign _093_ = clk_count[1] & clk_count[0];
  assign _094_ = clk_count[2] & _093_;
  assign _095_ = clk_count[3] & _094_;
  assign _096_ = clk_count[4] & _095_;
  assign _097_ = clk_count[5] & _096_;
  assign _098_ = clk_count[6] & _097_;
  assign _099_ = clk_count[7] & _098_;
  assign _100_ = clk_count[8] & _099_;
  assign _101_ = clk_count[9] & _100_;
  assign _102_ = clk_count[10] & _101_;
  assign _103_ = clk_count[11] & _102_;
  assign _104_ = clk_count[12] & _103_;
  assign _105_ = clk_count[13] & _104_;
  assign _106_ = ~(clk_count[14] & _105_);
  assign _107_ = state[2] | state[4];
  assign _108_ = state[3] | _107_;
  assign _109_ = clk_count[14] ^ _105_;
  assign _131_ = _108_ & _109_;
  assign _110_ = clk_count[13] ^ _104_;
  assign _130_ = _108_ & _110_;
  assign _111_ = ~(clk_count[14] | clk_count[15]);
  assign _112_ = ~(clk_count[13] | clk_count[11]);
  assign _113_ = ~(clk_count[8] | clk_count[9]);
  assign _114_ = _112_ & _113_;
  assign _115_ = _111_ & _114_;
  assign _116_ = clk_count[6] & clk_count[4];
  assign _117_ = clk_count[10] & _116_;
  assign _009_ = ~(clk_count[7] | clk_count[5]);
  assign _010_ = clk_count[12] & ~(clk_count[3]);
  assign _011_ = _009_ & _010_;
  assign _012_ = _117_ & _011_;
  assign _013_ = _094_ & _012_;
  assign _014_ = _115_ & _013_;
  assign _015_ = _107_ & ~(_014_);
  assign _016_ = state[3] | _015_;
  assign _017_ = clk_count[12] ^ _103_;
  assign _129_ = _016_ & _017_;
  assign _018_ = ~(clk_count[6] | clk_count[4]);
  assign _019_ = ~(clk_count[2] | clk_count[10]);
  assign _020_ = _018_ & _019_;
  assign _021_ = clk_count[5] & clk_count[3];
  assign _022_ = ~(clk_count[13] | clk_count[8]);
  assign _023_ = _111_ & _022_;
  assign _024_ = clk_count[11] & clk_count[9];
  assign _025_ = _093_ & _024_;
  assign _026_ = _023_ & _025_;
  assign _027_ = ~(clk_count[7] | clk_count[12]);
  assign _028_ = _020_ & _027_;
  assign _029_ = _026_ & _028_;
  assign _030_ = ~(_021_ & _029_);
  assign _031_ = ~(state[3] & _030_);
  assign _032_ = _107_ | ~(_031_);
  assign _033_ = clk_count[11] ^ _102_;
  assign _128_ = _032_ & _033_;
  assign _034_ = clk_count[10] ^ _101_;
  assign _127_ = _016_ & _034_;
  assign _035_ = clk_count[9] ^ _100_;
  assign _141_ = _032_ & _035_;
  assign _036_ = clk_count[8] ^ _099_;
  assign _140_ = _108_ & _036_;
  assign _037_ = clk_count[7] ^ _098_;
  assign _139_ = _108_ & _037_;
  assign _038_ = clk_count[6] ^ _097_;
  assign _138_ = _016_ & _038_;
  assign _039_ = clk_count[5] ^ _096_;
  assign _137_ = _032_ & _039_;
  assign _040_ = clk_count[4] ^ _095_;
  assign _136_ = _016_ & _040_;
  assign _041_ = _015_ | ~(_031_);
  assign _042_ = clk_count[3] ^ _094_;
  assign _135_ = _041_ & _042_;
  assign _043_ = clk_count[2] ^ _093_;
  assign _134_ = _032_ & _043_;
  assign _044_ = clk_count[1] ^ clk_count[0];
  assign _133_ = _108_ & _044_;
  assign _126_ = _092_ & _108_;
  assign _045_ = bit_count[1] & ~(bit_count[0]);
  assign _046_ = bit_count[2] & _045_;
  assign _124_ = _046_ ? rx : rx_shift[6];
  assign _047_ = bit_count[0] & ~(bit_count[1]);
  assign _048_ = bit_count[2] & _047_;
  assign _123_ = _048_ ? rx : rx_shift[5];
  assign _049_ = ~(bit_count[1] | bit_count[0]);
  assign _050_ = bit_count[2] & _049_;
  assign _122_ = _050_ ? rx : rx_shift[4];
  assign _051_ = _045_ | _047_;
  assign _052_ = bit_count[1] & bit_count[0];
  assign _053_ = bit_count[2] | ~(_052_);
  assign _054_ = ~(rx_shift[3] & _053_);
  assign _055_ = ~(bit_count[2] ^ _049_);
  assign _056_ = rx & _052_;
  assign _057_ = ~(_055_ & _056_);
  assign _121_ = ~(_054_ & _057_);
  assign _058_ = _045_ & ~(bit_count[2]);
  assign _120_ = _058_ ? rx : rx_shift[2];
  assign _059_ = _047_ & ~(bit_count[2]);
  assign _119_ = _059_ ? rx : rx_shift[1];
  assign _060_ = _049_ & ~(bit_count[2]);
  assign _118_ = _060_ ? rx : rx_shift[0];
  assign _143_ = state[2] & _051_;
  assign _142_ = state[2] & ~(bit_count[0]);
  assign _061_ = state[2] & ~(reset);
  assign _062_ = ~(bit_count[2] & _052_);
  assign _063_ = _014_ & ~(_062_);
  assign _064_ = _063_ | ~(_061_);
  assign _065_ = ~(reset | rx);
  assign _066_ = state[3] & ~(_030_);
  assign _067_ = ~(_065_ & _066_);
  assign _002_ = ~(_064_ & _067_);
  assign _068_ = rx & state[4];
  assign _008_ = _014_ & _068_;
  assign _000_ = _008_ & ~(reset);
  assign _069_ = state[0] | _066_;
  assign _070_ = ~(rx & _069_);
  assign _071_ = state[4] & _065_;
  assign _072_ = ~(_014_ & _071_);
  assign _073_ = ~(reset | state[1]);
  assign _074_ = _072_ & _073_;
  assign _001_ = ~(_070_ & _074_);
  assign _005_ = state[2] & _014_;
  assign _145_ = state[0] & ~(rx);
  assign _075_ = ~(clk_count[15] ^ _106_);
  assign _132_ = _108_ & _075_;
  assign _076_ = _014_ | ~(state[4]);
  assign _077_ = rx ? state[4] : state[3];
  assign _078_ = ~(state[2] | _077_);
  assign _079_ = _076_ & _078_;
  assign _007_ = _031_ & _079_;
  assign _080_ = reset | _076_;
  assign _081_ = ~(_061_ & _063_);
  assign _004_ = ~(_080_ & _081_);
  assign _082_ = ~(_014_ & _062_);
  assign _083_ = ~(state[2] & _082_);
  assign _084_ = ~(state[3] & rx);
  assign _085_ = ~(state[4] | state[1]);
  assign _086_ = _084_ & _085_;
  assign _087_ = _031_ & _086_;
  assign _006_ = _083_ & _087_;
  assign _088_ = ~(rx_shift[7] & _062_);
  assign _089_ = _055_ | ~(_056_);
  assign _125_ = ~(_088_ & _089_);
  assign _090_ = _031_ & ~(_145_);
  assign _003_ = ~(reset | _090_);
  assign _091_ = bit_count[2] ^ _052_;
  assign _144_ = state[2] & _091_;
  always @(posedge clk)
    state[0] <= _001_;
  always @(posedge clk)
    state[1] <= _000_;
  always @(posedge clk)
    state[2] <= _002_;
  always @(posedge clk)
    state[3] <= _003_;
  always @(posedge clk)
    state[4] <= _004_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_data[0] <= 1'h0;
    else if (_008_) rx_data[0] <= rx_shift[0];
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_data[1] <= 1'h0;
    else if (_008_) rx_data[1] <= rx_shift[1];
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_data[2] <= 1'h0;
    else if (_008_) rx_data[2] <= rx_shift[2];
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_data[3] <= 1'h0;
    else if (_008_) rx_data[3] <= rx_shift[3];
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_data[4] <= 1'h0;
    else if (_008_) rx_data[4] <= rx_shift[4];
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_data[5] <= 1'h0;
    else if (_008_) rx_data[5] <= rx_shift[5];
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_data[6] <= 1'h0;
    else if (_008_) rx_data[6] <= rx_shift[6];
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_data[7] <= 1'h0;
    else if (_008_) rx_data[7] <= rx_shift[7];
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_done <= 1'h0;
    else rx_done <= state[1];
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_busy <= 1'h0;
    else if (_007_) rx_busy <= _145_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) bit_count[0] <= 1'h0;
    else if (_006_) bit_count[0] <= _142_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) bit_count[1] <= 1'h0;
    else if (_006_) bit_count[1] <= _143_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) bit_count[2] <= 1'h0;
    else if (_006_) bit_count[2] <= _144_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) clk_count[0] <= 1'h0;
    else if (!state[1]) clk_count[0] <= _126_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) clk_count[1] <= 1'h0;
    else if (!state[1]) clk_count[1] <= _133_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) clk_count[2] <= 1'h0;
    else if (!state[1]) clk_count[2] <= _134_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) clk_count[3] <= 1'h0;
    else if (!state[1]) clk_count[3] <= _135_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) clk_count[4] <= 1'h0;
    else if (!state[1]) clk_count[4] <= _136_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) clk_count[5] <= 1'h0;
    else if (!state[1]) clk_count[5] <= _137_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) clk_count[6] <= 1'h0;
    else if (!state[1]) clk_count[6] <= _138_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) clk_count[7] <= 1'h0;
    else if (!state[1]) clk_count[7] <= _139_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) clk_count[8] <= 1'h0;
    else if (!state[1]) clk_count[8] <= _140_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) clk_count[9] <= 1'h0;
    else if (!state[1]) clk_count[9] <= _141_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) clk_count[10] <= 1'h0;
    else if (!state[1]) clk_count[10] <= _127_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) clk_count[11] <= 1'h0;
    else if (!state[1]) clk_count[11] <= _128_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) clk_count[12] <= 1'h0;
    else if (!state[1]) clk_count[12] <= _129_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) clk_count[13] <= 1'h0;
    else if (!state[1]) clk_count[13] <= _130_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) clk_count[14] <= 1'h0;
    else if (!state[1]) clk_count[14] <= _131_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) clk_count[15] <= 1'h0;
    else if (!state[1]) clk_count[15] <= _132_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_shift[0] <= 1'h0;
    else if (_005_) rx_shift[0] <= _118_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_shift[1] <= 1'h0;
    else if (_005_) rx_shift[1] <= _119_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_shift[2] <= 1'h0;
    else if (_005_) rx_shift[2] <= _120_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_shift[3] <= 1'h0;
    else if (_005_) rx_shift[3] <= _121_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_shift[4] <= 1'h0;
    else if (_005_) rx_shift[4] <= _122_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_shift[5] <= 1'h0;
    else if (_005_) rx_shift[5] <= _123_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_shift[6] <= 1'h0;
    else if (_005_) rx_shift[6] <= _124_;
  (* src = "rtl/uart_rx.v:48.5-233.8" *)
  always @(posedge clk)
    if (reset) rx_shift[7] <= 1'h0;
    else if (_005_) rx_shift[7] <= _125_;
endmodule

(* top =  1  *)
(* src = "rtl/uart_top.v:4.1-78.10" *)
module uart_top(clk, reset, tx_start, tx_data, tx, tx_busy, tx_done, rx, rx_data, rx_done, rx_busy);
  (* src = "rtl/uart_top.v:8.23-8.26" *)
  input clk;
  wire clk;
  (* src = "rtl/uart_top.v:9.23-9.28" *)
  input reset;
  wire reset;
  (* src = "rtl/uart_top.v:12.23-12.31" *)
  input tx_start;
  wire tx_start;
  (* src = "rtl/uart_top.v:13.23-13.30" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "rtl/uart_top.v:14.23-14.25" *)
  output tx;
  wire tx;
  (* src = "rtl/uart_top.v:15.23-15.30" *)
  output tx_busy;
  wire tx_busy;
  (* src = "rtl/uart_top.v:16.23-16.30" *)
  output tx_done;
  wire tx_done;
  (* src = "rtl/uart_top.v:19.23-19.25" *)
  input rx;
  wire rx;
  (* src = "rtl/uart_top.v:20.23-20.30" *)
  output [7:0] rx_data;
  wire [7:0] rx_data;
  (* src = "rtl/uart_top.v:21.23-21.30" *)
  output rx_done;
  wire rx_done;
  (* src = "rtl/uart_top.v:22.23-22.30" *)
  output rx_busy;
  wire rx_busy;
  (* src = "rtl/uart_top.v:29.10-29.18" *)
  wire bit_tick;
  (* src = "rtl/uart_top.v:39.7-43.6" *)
  \$paramod$b7294f1997723f0618629b64f4b039e150234139\baud_tick_gen  baud_gen_inst (
    .bit_tick(bit_tick),
    .clk(clk),
    .reset(reset)
  );
  (* src = "rtl/uart_top.v:69.7-76.6" *)
  \$paramod$b7294f1997723f0618629b64f4b039e150234139\uart_rx  rx_inst (
    .clk(clk),
    .reset(reset),
    .rx(rx),
    .rx_busy(rx_busy),
    .rx_data(rx_data),
    .rx_done(rx_done)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/uart_top.v:50.13-59.6" *)
  uart_tx tx_inst (
    .bit_tick(bit_tick),
    .clk(clk),
    .reset(reset),
    .tx(tx),
    .tx_busy(tx_busy),
    .tx_data(tx_data),
    .tx_done(tx_done),
    .tx_start(tx_start)
  );
endmodule

(* src = "rtl/uart_tx.v:4.1-195.10" *)
module uart_tx(clk, reset, tx_start, tx_data, bit_tick, tx, tx_busy, tx_done);
  (* src = "rtl/uart_tx.v:8.23-8.26" *)
  input clk;
  wire clk;
  (* src = "rtl/uart_tx.v:9.23-9.28" *)
  input reset;
  wire reset;
  (* src = "rtl/uart_tx.v:11.23-11.31" *)
  input tx_start;
  wire tx_start;
  (* src = "rtl/uart_tx.v:12.23-12.30" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "rtl/uart_tx.v:14.23-14.31" *)
  input bit_tick;
  wire bit_tick;
  (* src = "rtl/uart_tx.v:16.23-16.25" *)
  output tx;
  reg tx;
  (* src = "rtl/uart_tx.v:17.23-17.30" *)
  output tx_busy;
  reg tx_busy;
  (* src = "rtl/uart_tx.v:18.23-18.30" *)
  output tx_done;
  reg tx_done;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  (* src = "rtl/uart_tx.v:39.15-39.24" *)
  reg [2:0] bit_count;
  (* onehot = 32'd1 *)
  reg [3:0] state;
  (* src = "rtl/uart_tx.v:37.15-37.27" *)
  reg [7:0] tx_shift_reg;
  assign _009_ = ~tx_start;
  assign _044_ = state[1] ? tx_shift_reg[4] : tx_data[3];
  assign _043_ = state[1] ? tx_shift_reg[3] : tx_data[2];
  assign _045_ = state[1] ? tx_shift_reg[5] : tx_data[4];
  assign _042_ = state[1] ? tx_shift_reg[2] : tx_data[1];
  assign _041_ = state[1] ? tx_shift_reg[1] : tx_data[0];
  assign _046_ = state[1] ? tx_shift_reg[6] : tx_data[5];
  assign _010_ = bit_count[1] & bit_count[0];
  assign _011_ = bit_count[1] | bit_count[0];
  assign _012_ = state[1] & _011_;
  assign _039_ = _012_ & ~(_010_);
  assign _038_ = state[1] & ~(bit_count[0]);
  assign _008_ = state[1] & tx_shift_reg[0];
  assign _047_ = state[1] ? tx_shift_reg[7] : tx_data[6];
  assign _013_ = ~(state[1] | state[2]);
  assign _006_ = reset | _013_;
  assign _014_ = bit_tick & ~(reset);
  assign _015_ = ~(bit_count[2] & _010_);
  assign _016_ = state[1] & _015_;
  assign _017_ = state[2] | _016_;
  assign _018_ = ~(_014_ & _017_);
  assign _019_ = ~(reset | bit_tick);
  assign _020_ = ~(state[1] & _019_);
  assign _001_ = ~(_018_ & _020_);
  assign _021_ = tx_start | ~(state[0]);
  assign _022_ = bit_tick & state[3];
  assign _023_ = ~(reset | _022_);
  assign _000_ = ~(_021_ & _023_);
  assign _024_ = bit_tick | ~(state[2]);
  assign _025_ = ~(tx_start & state[0]);
  assign _026_ = _024_ & _025_;
  assign _002_ = ~(reset | _026_);
  assign _027_ = bit_count[2] | _010_;
  assign _040_ = _016_ & _027_;
  assign _048_ = tx_data[7] & ~(state[1]);
  assign _028_ = ~(bit_tick & _015_);
  assign _029_ = ~(state[1] & _028_);
  assign _030_ = state[0] ? tx_start : state[1];
  assign _005_ = _029_ & _030_;
  assign _031_ = state[0] | ~(_013_);
  assign _032_ = _024_ & _031_;
  assign _004_ = _029_ & _032_;
  assign _007_ = reset | ~(state[3]);
  assign _033_ = bit_tick | _007_;
  assign _034_ = ~(state[1] & _014_);
  assign _035_ = _015_ | _034_;
  assign _003_ = ~(_033_ & _035_);
  assign _036_ = state[0] ? _009_ : bit_tick;
  assign _037_ = ~(_013_ & _036_);
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  always @(posedge clk)
    if (_006_) tx <= 1'h1;
    else tx <= _008_;
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  always @(posedge clk)
    if (_007_) tx_done <= 1'h0;
    else tx_done <= bit_tick;
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  always @(posedge clk)
    if (reset) tx_busy <= 1'h0;
    else tx_busy <= _037_;
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  always @(posedge clk)
    if (reset) tx_shift_reg[0] <= 1'h0;
    else if (_005_) tx_shift_reg[0] <= _041_;
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  always @(posedge clk)
    if (reset) tx_shift_reg[1] <= 1'h0;
    else if (_005_) tx_shift_reg[1] <= _042_;
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  always @(posedge clk)
    if (reset) tx_shift_reg[2] <= 1'h0;
    else if (_005_) tx_shift_reg[2] <= _043_;
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  always @(posedge clk)
    if (reset) tx_shift_reg[3] <= 1'h0;
    else if (_005_) tx_shift_reg[3] <= _044_;
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  always @(posedge clk)
    if (reset) tx_shift_reg[4] <= 1'h0;
    else if (_005_) tx_shift_reg[4] <= _045_;
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  always @(posedge clk)
    if (reset) tx_shift_reg[5] <= 1'h0;
    else if (_005_) tx_shift_reg[5] <= _046_;
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  always @(posedge clk)
    if (reset) tx_shift_reg[6] <= 1'h0;
    else if (_005_) tx_shift_reg[6] <= _047_;
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  always @(posedge clk)
    if (reset) tx_shift_reg[7] <= 1'h0;
    else if (_005_) tx_shift_reg[7] <= _048_;
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  always @(posedge clk)
    if (reset) bit_count[0] <= 1'h0;
    else if (_004_) bit_count[0] <= _038_;
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  always @(posedge clk)
    if (reset) bit_count[1] <= 1'h0;
    else if (_004_) bit_count[1] <= _039_;
  (* src = "rtl/uart_tx.v:46.5-193.8" *)
  always @(posedge clk)
    if (reset) bit_count[2] <= 1'h0;
    else if (_004_) bit_count[2] <= _040_;
  always @(posedge clk)
    state[0] <= _000_;
  always @(posedge clk)
    state[1] <= _001_;
  always @(posedge clk)
    state[2] <= _002_;
  always @(posedge clk)
    state[3] <= _003_;
endmodule
